/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iqa;

/**
 *
 * @author b1zon
 */
public class FrontEnd extends javax.swing.JFrame {
    
    private Calculos c;
    /**
     * Creates new form FrontEnd
     */
    public FrontEnd() {
        initComponents();
        c = new Calculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solidoF = new javax.swing.JTextField();
        turbidezF = new javax.swing.JTextField();
        coliformeF = new javax.swing.JTextField();
        dboF = new javax.swing.JTextField();
        nitrogenioF = new javax.swing.JTextField();
        fosforoF = new javax.swing.JTextField();
        phF = new javax.swing.JTextField();
        temperaturaF = new javax.swing.JTextField();
        oxigenioF = new javax.swing.JTextField();
        altitudeF = new javax.swing.JTextField();
        variacaoF = new javax.swing.JTextField();
        calculaIQA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        resultadoF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        solidoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solidoFActionPerformed(evt);
            }
        });

        turbidezF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turbidezFActionPerformed(evt);
            }
        });

        coliformeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coliformeFActionPerformed(evt);
            }
        });

        dboF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dboFActionPerformed(evt);
            }
        });

        nitrogenioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitrogenioFActionPerformed(evt);
            }
        });

        fosforoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fosforoFActionPerformed(evt);
            }
        });

        phF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phFActionPerformed(evt);
            }
        });

        temperaturaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturaFActionPerformed(evt);
            }
        });

        variacaoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variacaoFActionPerformed(evt);
            }
        });

        calculaIQA.setText("Resultado");
        calculaIQA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaIQAActionPerformed(evt);
            }
        });

        jLabel1.setText("INSIRA OS VALORES ABAIXO PARA QUE O IQA SEJA CALCULADO");

        jLabel2.setText("Sólidos");

        jLabel3.setText("Turbidez");

        jLabel4.setText("Coliformes");

        jLabel5.setText("DBO");

        jLabel6.setText("Nitrogênio");

        jLabel7.setText("Fósforo");

        jLabel8.setText("PH");

        jLabel9.setText("Temp");

        jLabel10.setText("Oxigênio");

        jLabel11.setText("Altitude");

        jLabel12.setText("Se ouver variação na temperatura inserir na caixa a frente:");

        resultadoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(solidoF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(turbidezF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(coliformeF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculaIQA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dboF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(nitrogenioF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(fosforoF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(phF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(temperaturaF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oxigenioF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(variacaoF)
                    .addComponent(altitudeF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(solidoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(turbidezF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coliformeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dboF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nitrogenioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fosforoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temperaturaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(oxigenioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(altitudeF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculaIQA)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(variacaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coliformeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coliformeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coliformeFActionPerformed

    private void turbidezFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turbidezFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turbidezFActionPerformed

    private void dboFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dboFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dboFActionPerformed

    private void nitrogenioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitrogenioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitrogenioFActionPerformed

    private void fosforoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fosforoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fosforoFActionPerformed

    private void phFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phFActionPerformed

    private void temperaturaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperaturaFActionPerformed

    private void variacaoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variacaoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variacaoFActionPerformed

    private void solidoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solidoFActionPerformed
           
    }//GEN-LAST:event_solidoFActionPerformed

    private void calculaIQAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaIQAActionPerformed

        try{
           c.Solidos(Double.parseDouble(solidoF.getText())); 
           System.out.println("O resultado do getSolidos foi: " + c.getSolidos());
           
           c.Turbidez(Double.parseDouble(turbidezF.getText())); 
           System.out.println("O resultado do getTurbidez foi: " + c.getTurbidez());
           
           c.Coliformes(Double.parseDouble(coliformeF.getText()));
           System.out.println("O resultado do getColiformes foi: " + c.getColiformes());
           
           c.DBO(Double.parseDouble(dboF.getText())); 
           System.out.println("O resultado do getDBO foi: " + c.getDbo());
           
           c.Nitrato(Double.parseDouble(nitrogenioF.getText()));
           System.out.println("O resultado do getNitratro foi: " + c.getNitrato());
           
           c.Fosfato(Double.parseDouble(fosforoF.getText()));
           System.out.println("O resultado do getFosfato foi: " + c.getFosfato());
           
           c.Ph(Double.parseDouble(phF.getText()));
           System.out.println("O resultado do getPh foi: " + c.getPh());
           
           c.Variacao(Double.parseDouble(variacaoF.getText()));
           System.out.println("O resultado do getVariacao foi: " + c.getVariacao());
           
           c.setAltitude(Double.parseDouble(altitudeF.getText())); 
           System.out.println("O resultado do getAltitude foi: " + c.getAltitude());
           
           c.setTemperatura(Double.parseDouble(temperaturaF.getText()));
           System.out.println("O resultado do getTemperatura foi: " + c.getTemperatura());
           
           c.Oxigenio(Double.parseDouble(oxigenioF.getText())); 
           System.out.println("O resultado do getOxigenio foi: " + c.getOxigenio());
           
           c.IQA();
           System.out.println("O resultado do IQA foi: " + c.getIqa());
           
        }catch(NumberFormatException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_calculaIQAActionPerformed

    private void resultadoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoFActionPerformed
        try{
            resultadoF.setText(Double.toString(c.getIqa()));
        }catch(NumberFormatException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_resultadoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontEnd().setVisible(true);
                
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altitudeF;
    private javax.swing.JButton calculaIQA;
    private javax.swing.JTextField coliformeF;
    private javax.swing.JTextField dboF;
    private javax.swing.JTextField fosforoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nitrogenioF;
    private javax.swing.JTextField oxigenioF;
    private javax.swing.JTextField phF;
    private javax.swing.JTextField resultadoF;
    private javax.swing.JTextField solidoF;
    private javax.swing.JTextField temperaturaF;
    private javax.swing.JTextField turbidezF;
    private javax.swing.JTextField variacaoF;
    // End of variables declaration//GEN-END:variables
}
